version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.10
  working_directory: ~/circleci-deployment

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn build

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: cp .npmrc-ci .npmrc
      - run: yarn build
      - run: npm publish --access public

workflows:
  version: 2
  all:
    jobs:
      - install:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release:
          requires:
            - install
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
